# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.3

# Site settings
title:      Simply Confessions
logo:        # Logo Image URL
description: A blog about philosophy and psychology.
baseurl:     '' # The subpath of your site, e.g. /blog
url:         https://www.simplyconfessions.com # The base hostname & protocol for your site
twitter:     https://twitter.com/simplyconfess_
instagram:   https://www.instagram.com/_simply_confessions_/

markdown:  kramdown
permalink: pretty
paginate:  9
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:        tag
tag_page_layout:     tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Nickie:
    name:     Nickie
    bio:
    gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:    simplyconfessions00@gmail.com
    website:  http://aspirethemes.com
    github:   https://www.github.com/aspirethemes
    twitter:  https://twitter.com/aspirethemes
